ProgettoBackend-S2-L5/Controllers/ArticoliController.cs
using System.Diagnostics;
using System.Diagnostics.Metrics;
using System.Drawing;
using System.Globalization;
using System.Reflection;
using System.Runtime.ConstrainedExecution;
using Microsoft.AspNetCore.Mvc;
using ProgettoBackend_S2_L5.Models;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace ProgettoBackend_S2_L5.Controllers
{
    public class ArticoliController : Controller
    {
        private static List<Articolo> articoli = new List<Articolo>
        {

            new()
            {
                Id = Guid.NewGuid(),
                Nome = "Nike Air Max DN",
                Prezzo = 94.99m,
                Descrizione = "La scarpa integra il nostro sistema di unità Dynamic Air con due set di tubi a doppia pressione. Abbiamo regolato ogni set a un livello di pressione diverso, con la più ferma nel tallone e la più morbida sotto il centro del piede. L'aria si sposta all'interno con ogni tuo passo creando una transizione fluida.",
                Copertina = "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/7dc5794a-ce40-4bf2-bb8f-32cb8be866ea/AIR+MAX+DN+%28GS%29.png",
                Immagine2 = "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/e0e74245-af19-49b7-a261-a72b2cfc592d/AIR+MAX+DN+%28GS%29.png",
                Immagine3 = "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/765d660d-d882-4115-bb58-19f54f4a8018/AIR+MAX+DN+%28GS%29.png"

            },

            new()
            {
                Id = Guid.NewGuid(),
                Nome = "Nike Air Max",
                Prezzo = 189.99m,
                Descrizione = "La tomaia in materiale sintetico, con mesh traspirante, offre comfort, leggerezza e resistenza. " +
                "Originariamente concepita per il running ad alte prestazioni, l'unità Nike Air offre leggerezza e un'ammortizzazione che dura nel tempo. " +
                "Per portare la vita da spiaggia in città, il prominente arco in TPU ricorda la coda di una balena e aggiunge struttura, mentre le iconiche dita in TPU richiamano le palme e le onde dell'oceano. " +
                 "TPU sulla punta per una maggiore resistenza e un tocco di lucentezza.",
                Copertina = "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/877d30e7-4880-46f8-aa71-6704eb7d944d/AIR+MAX+PLUS.png",
                Immagine2 = "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/94ee6b23-9c33-437a-8992-a5aa06436ada/NIKE+AIR+MAX+PLUS.png",
                Immagine3 = "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/47b7945e-a379-4c24-b9df-98f4eef178e5/NIKE+AIR+MAX+PLUS.png"

            },

            new()
            {
                Id = Guid.NewGuid(),
                Nome = "Nike Dunk Low",
                Prezzo = 71.99m,
                Descrizione = "Tomaia in pelle dalla leggera lucentezza che offre, con il passare del tempo, una morbidezza ideale e presenta strati esterni resistenti che richiamano il basket anni Ottanta. Intersuola in schiuma per un'ammortizzazione leggera e reattiva. Collare imbottito a taglio basso per comfort ed eleganza. Vivaci blocchi di colore su alcuni modelli per rievocare i colori University della prima edizione del 1985 e darti la possibilità di scegliere una scarpa leggendaria per fare il tifo per la tua squadra. Battistrada in gomma, con classico punto di torsione per il basket, per resistenza, trazione e uno stile leggendario.",
                Copertina = "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/a447e0eb-b47c-464b-91df-5387f958582d/W+NIKE+DUNK+LOW.png",
                Immagine2 = "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/55f3633a-8a97-4592-8418-ae94e9ae999d/W+NIKE+DUNK+LOW+NEXT+NATURE.png",
                Immagine3 = "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/86421db8-3873-4535-82dc-764e3c5211a6/W+NIKE+DUNK+LOW.png"

            }
        };


        public IActionResult Index()
        {
            var listaArt = new ArticoliViewModel()
            {
                Articoli = articoli
            };
            return View(listaArt);
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(AddArticoloModel addArticoloModel)
        {
            if (!ModelState.IsValid)
            {
                TempData["Error"] = "Try again!";
                return RedirectToAction("Add");
            }

            var prezzoString = addArticoloModel.Prezzo.ToString(CultureInfo.InvariantCulture);
            if (!decimal.TryParse(prezzoString, NumberStyles.Any, CultureInfo.InvariantCulture, out decimal prezzo))
            {
                TempData["Error"] = "Formato prezzo non valido";
                return RedirectToAction("Add");
            }

            var nuovoArticolo = new Articolo()
            {
                Id = Guid.NewGuid(),
                Nome = addArticoloModel.Nome,
                Descrizione = addArticoloModel.Descrizione,
                Prezzo = prezzo,
                Copertina = addArticoloModel.Copertina,
                Immagine2 = addArticoloModel.Immagine2,
                Immagine3 = addArticoloModel.Immagine3,
            };

            articoli.Add(nuovoArticolo);

            TempData["Success"] = "Articolo aggiunto con successo!";
            return RedirectToAction("Index");
        }

        [HttpGet("/articoli/info/{id:guid}")]
        public IActionResult Info(Guid id)
        {
            var articoloEsistente = articoli.FirstOrDefault(a => a.Id == id);
            if (articoloEsistente == null)
            {
                TempData["Error"] = "Articolo non trovato!";
                return RedirectToAction("Index");
            }

            var infoArticolo = new InfoArticolo()
            {
                Id = articoloEsistente.Id,
                Nome = articoloEsistente.Nome,
                Descrizione = articoloEsistente.Descrizione,
                Prezzo = articoloEsistente.Prezzo,
                Copertina = articoloEsistente.Copertina,
                Immagine2 = articoloEsistente.Immagine2,
                Immagine3 = articoloEsistente.Immagine3
            };

            return View(infoArticolo);
        }

        [HttpGet("/articoli/modifica/{id:guid}")]
        public IActionResult Modifica(Guid id)
        {
            var articoloEsistente = articoli.FirstOrDefault(a => a.Id == id);
            if (articoloEsistente == null)
            {
                TempData["Error"] = "Articolo non trovato!";
                return RedirectToAction("Index");
            }

            var modificaArticolo = new ModificaArticoloModel()
            {
                Id = articoloEsistente.Id,
                Nome = articoloEsistente.Nome,
                Descrizione = articoloEsistente.Descrizione,
                Prezzo = articoloEsistente.Prezzo,
                Copertina = articoloEsistente.Copertina,
                Immagine2 = articoloEsistente.Immagine2,
                Immagine3 = articoloEsistente.Immagine3
            };

            return View(modificaArticolo);
        }

        [HttpPost("articolo/edit/{id:guid}")]
        public IActionResult Edit(Guid id, ModificaArticoloModel modificaArticoloModel)
        {
            var articoloModificato = articoli.FirstOrDefault(a => a.Id == id);

            if (articoloModificato == null)
            {
                TempData["Error"] = "Product not found";
                return RedirectToAction("Index");
            }

            var prezzoString = modificaArticoloModel.Prezzo.ToString(CultureInfo.InvariantCulture);
            if (decimal.TryParse(prezzoString, NumberStyles.Any, CultureInfo.InvariantCulture, out decimal prezzo))
            {
                articoloModificato.Prezzo = prezzo;
            }
            else
            {
                TempData["Error"] = "Formato prezzo non valido";
                return RedirectToAction("Edit", new { id });
            }

            articoloModificato.Nome = modificaArticoloModel.Nome;
            articoloModificato.Descrizione = modificaArticoloModel.Descrizione;
            if (!string.IsNullOrEmpty(modificaArticoloModel.Copertina))
            {
                articoloModificato.Copertina = modificaArticoloModel.Copertina;
            }
            articoloModificato.Immagine2 = modificaArticoloModel.Immagine2;
            articoloModificato.Immagine3 = modificaArticoloModel.Immagine3;

            return RedirectToAction("Index");
        }

        [HttpPost("articoli/elimina/{id:guid}")]
        public IActionResult Elimina(Guid id)
        {
            var articolo = articoli.FirstOrDefault(a => a.Id == id);
            if (articolo == null)
            {
                TempData["Error"] = "Product not found";
                return RedirectToAction("Index");
            }

            articoli.Remove(articolo);  
            TempData["Success"] = "Prodotto eliminato con success!";

            return RedirectToAction("Index");  
        }
    }
}

ProgettoBackend-S2-L5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Scarpe&Co.</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProgettoBackend_S2_L5.styles.css" asp-append-version="true" />
</head>
<body>
    <header class="position-sticky sticky-top top-0">
        <nav class="navbar navbar-expand-sm py-0 navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 ">
            <div class="container-fluid">
                <a class="navbar-brand" class="w-50" asp-area="" asp-controller="Home" asp-action="Index"><img src="https://www.scarpe.pt/wp-content/uploads/2024/04/SCARPE-LOGO.png" class="logo" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Articoli" asp-action="Index">Articoli</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted py-3 text-center">
        <div class="container">
            &copy; 2025 - Scarpe&Co. - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>